swagger: "2.0"
info:
   title: Bank Argent API documentation
   description: Contains all available API endpoints in this codebase
   version: "1.0.0"
   termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
   - http
paths:
   /user/login:
      post:
         tags:
            - User Module
         summary: Login
         description: API for Login
         parameters:
            - in: body
              name: body
              description: Login Payload
              required: true
              schema:
                 $ref: "#/definitions/Login"
         produces:
            - application/json
         responses:
            "200":
               description: Login Successfully
               schema:
                  $ref: "#/definitions/LoginResponse"
            "400":
               description: Invalid Fields
            "500":
               description: Internal Server Error
   /user/signup:
      post:
         tags:
            - User Module
         summary: Signup
         description: API for Signup
         parameters:
            - in: body
              name: body
              description: Signup Payload
              required: true
              schema:
                 $ref: "#/definitions/User"
         produces:
            - application/json
         responses:
            "200":
               description: Signup Successfully
               schema:
                  $ref: "#/definitions/ApiResponse"
            "400":
               description: Invalid Fields
            "500":
               description: Internal Server Error
   /user/profile:
      get:
         security:
            - BearerAuth: []
         tags:
            - User Module
         summary: User Profile API
         description: API for fetching a user profile
         produces:
            - application/json
         responses:
            "200":
               description: User profile retrieved successfully
               schema:
                  $ref: "#/definitions/UserProfile"
            "401":
               description: Unauthorized
            "500":
               description: Internal Server Error
      put:
         security:
            - BearerAuth: []
         tags:
            - User Module
         summary: Update User Profile
         description: Update user profile attributes
         parameters:
            - in: body
              name: body
              description: Update Payload
              required: true
              schema:
                 $ref: "#/definitions/UserProfile"
         produces:
            - application/json
         responses:
            "200":
               description: User profile updated successfully
            "400":
               description: Invalid request
   /transactions:
      get:
         security:
            - BearerAuth: []
         tags:
            - Transactions
         summary: Get all transactions
         description: Retrieve all transactions for the authenticated user.
         produces:
            - application/json
         responses:
            "200":
               description: List of transactions retrieved successfully
               schema:
                  $ref: "#/definitions/TransactionList"
            "401":
               description: Unauthorized
            "404":
               description: Not Found
   /transactions/{transactionId}:
      get:
         security:
            - BearerAuth: []
         tags:
            - Transactions
         summary: Get transaction details
         description: Retrieve details of a specific transaction by ID.
         parameters:
            - name: transactionId
              in: path
              required: true
              type: string
              description: ID of the transaction to retrieve
         produces:
            - application/json
         responses:
            "200":
               description: Transaction details retrieved successfully
               schema:
                  $ref: "#/definitions/Transaction"
            "404":
               description: Transaction not found
      put:
         security:
            - BearerAuth: []
         tags:
            - Transactions
         summary: Update transaction
         description: Update category or note of a specific transaction.
         parameters:
            - name: transactionId
              in: path
              required: true
              type: string
              description: ID of the transaction to update
            - in: body
              name: transactionUpdate
              required: true
              schema:
                 $ref: "#/definitions/TransactionUpdate"
         produces:
            - application/json
         responses:
            "200":
               description: Transaction updated successfully
            "400":
               description: Invalid request
securityDefinitions:
   BearerAuth:
      type: apiKey
      name: Authorization
      in: header
definitions:
   User:
      properties:
         email:
            type: string
            description: user email
         password:
            type: string
            description: user password
         firstName:
            type: string
            description: user first name
         lastName:
            type: string
            description: user last name
         userName:
            type: string
            description: user public name
   Login:
      type: object
      properties:
         email:
            type: string
         password:
            type: string
   LoginResponse:
      type: object
      properties:
         token:
            type: string
   ApiResponse:
      type: object
      properties:
         status:
            type: integer
         message:
            type: string
         body:
            type: object
            properties:
               id:
                  type: string
               email:
                  type: string
   UserProfile:
      type: object
      properties:
         firstName:
            type: string
         lastName:
            type: string
         userName:
            type: string
   TransactionList:
      type: array
      items:
         $ref: "#/definitions/Transaction"
   Transaction:
      type: object
      properties:
         id:
            type: string
         date:
            type: string
            format: date-time
         description:
            type: string
         amount:
            type: number
            format: float
         category:
            type: string
         note:
            type: string
   TransactionUpdate:
      type: object
      properties:
         category:
            type: string
         note:
            type: string
